### ISSUE TITLE
Incomplete / Non-Reproducible code

### ISSUE THREAD

**Issue by parth995** [dennisivy/crash-course-CRM#22]
Hey,
Can you update a latest code please ? Upon running localsever and clicking on buttons it doesnt make any actions effective. Not sure which branch to use

**Comment by sahil78272026** [comment]
what is the error you are facing? please elaborate and be specific.

**Comment by parth995** [comment]
First of all you must be specific in README.md file which branch to use and how to initiate server. I upon assuming Final-Project branch, while running "python3 manage.py runserver 127.0.0.1:8000" it throws error of modules as below. So you must be specific and later we can discuss about button click nothing works. Not sure it was fixed by you recently. I just pulled in code from "Final-Project" branch and it doesn't works

https://github.com/divanov11/crash-course-CRM --> Null URL with no code

Below is error

`
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/opt/homebrew/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/opt/homebrew/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/opt/homebrew/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/homebrew/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/opt/homebrew/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'widget_tweaks'
`
